// ============================================================
// MOCK DATA — Replace with real API calls as each service is built
// ============================================================

import type {
  User,
  SoulWallet,
  Transaction,
  Position,
  TradingBotConfig,
  TravelBooking,
} from '@/types'

export const MOCK_USER: User = {
  id: 'usr_01HXYZ123',
  name: 'Dominic Sovereign',
  email: 'd.sovereign@dustify.com',
  avatarUrl: null,
  kycLevel: 'ID_VERIFIED',
  createdAt: '2024-03-15T09:00:00Z',
}

export const MOCK_WALLET: SoulWallet = {
  id: 'sw_01HXYZ456',
  userId: 'usr_01HXYZ123',
  walletAddress: '0xD4AF3789AbCdEf012345678901234567890ABCDE',
  sbtTokenId: '847',
  mintedAt: '2024-03-15T09:12:00Z',
  usdcBalance: 28_420.54,
  pointsBalance: 48_200,
  rewardsTier: 'SURGE',
  tierUpdatedAt: '2024-12-01T00:00:00Z',
  isQuantumShielded: true,
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_001',
    type: 'TRADE_BOT',
    status: 'COMPLETED',
    amount: 75.00,
    feeAmount: 0.075,
    pointsAwarded: 15,
    description: 'Bot trade — BTC/USDC · 0.10% fee',
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    externalTxId: 'alp_btc_8842',
    metadata: { symbol: 'BTC', side: 'BUY' },
  },
  {
    id: 'txn_002',
    type: 'TRAVEL_FLIGHT',
    status: 'COMPLETED',
    amount: 748.00,
    feeAmount: 18.70,
    pointsAwarded: 150,
    description: 'Flight — JFK → LAX · Delta Air Lines',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    externalTxId: 'ama_flt_99234',
    metadata: { airline: 'Delta', route: 'JFK→LAX' },
  },
  {
    id: 'txn_003',
    type: 'TRADE_BOT',
    status: 'COMPLETED',
    amount: 120.00,
    feeAmount: 0.12,
    pointsAwarded: 15,
    description: 'Bot trade — ETH/USDC · 0.10% fee',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    externalTxId: 'alp_eth_8841',
    metadata: { symbol: 'ETH', side: 'SELL' },
  },
  {
    id: 'txn_004',
    type: 'CODE_DEPLOY',
    status: 'COMPLETED',
    amount: 0,
    feeAmount: 0,
    pointsAwarded: 100,
    description: 'Code deploy — Dust Studio API · Vercel',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    externalTxId: null,
    metadata: { project: 'dust-studio', platform: 'vercel' },
  },
  {
    id: 'txn_005',
    type: 'REFERRAL',
    status: 'COMPLETED',
    amount: 5.00,
    feeAmount: 0,
    pointsAwarded: 500,
    description: 'Referral bonus — User #1842 joined',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    externalTxId: null,
    metadata: { referredUserId: 'usr_01842' },
  },
  {
    id: 'txn_006',
    type: 'USDC_RECEIVE',
    status: 'COMPLETED',
    amount: 2_500.00,
    feeAmount: 0,
    pointsAwarded: 25,
    description: 'Received USDC · From 0xA3B2...C4D1',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    externalTxId: '0xabc123def456',
    metadata: { senderAddress: '0xA3B2...C4D1' },
  },
]

export const MOCK_POSITIONS: Position[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    assetClass: 'CRYPTO',
    quantity: 0.412,
    avgCostBasis: 58_200,
    currentPrice: 67_842,
    currentValue: 27_951,
    unrealizedPnl: 3_972,
    unrealizedPnlPct: 16.56,
    dayChangePct: 3.24,
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    assetClass: 'STOCK',
    quantity: 100,
    avgCostBasis: 165.30,
    currentPrice: 187.42,
    currentValue: 18_742,
    unrealizedPnl: 2_212,
    unrealizedPnlPct: 13.38,
    dayChangePct: 0.82,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    assetClass: 'CRYPTO',
    quantity: 4.2,
    avgCostBasis: 2_800,
    currentPrice: 3_420,
    currentValue: 14_364,
    unrealizedPnl: 2_604,
    unrealizedPnlPct: 22.14,
    dayChangePct: 2.18,
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corp.',
    assetClass: 'STOCK',
    quantity: 15,
    avgCostBasis: 620,
    currentPrice: 875.40,
    currentValue: 13_131,
    unrealizedPnl: 3_831,
    unrealizedPnlPct: 41.19,
    dayChangePct: -1.24,
  },
  {
    symbol: 'SPY',
    name: 'S&P 500 ETF',
    assetClass: 'ETF',
    quantity: 20,
    avgCostBasis: 490,
    currentPrice: 522.80,
    currentValue: 10_456,
    unrealizedPnl: 656,
    unrealizedPnlPct: 6.69,
    dayChangePct: 0.44,
  },
]

export const MOCK_BOT_CONFIG: TradingBotConfig = {
  isActive: true,
  riskTolerance: 'MODERATE',
  maxPositionSizePct: 10,
  maxDailyLossPct: 3,
  assetClasses: ['STOCK', 'CRYPTO', 'ETF'],
  tradingHours: 'CRYPTO_24_7',
  taxLossHarvestingEnabled: true,
  optionsEnabled: false,
}

export const MOCK_TRAVEL_BOOKINGS: TravelBooking[] = [
  {
    id: 'bk_001',
    type: 'FLIGHT',
    destination: 'Los Angeles, CA',
    departureDate: '2025-02-14T08:00:00Z',
    returnDate: '2025-02-18T22:00:00Z',
    totalPrice: 748.00,
    pointsEarned: 150,
    status: 'UPCOMING',
    confirmationCode: 'DL4892',
  },
  {
    id: 'bk_002',
    type: 'HOTEL',
    destination: 'Los Angeles, CA',
    departureDate: '2025-02-14T15:00:00Z',
    returnDate: '2025-02-18T11:00:00Z',
    totalPrice: 1_240.00,
    pointsEarned: 248,
    status: 'UPCOMING',
    confirmationCode: 'HTL99821',
  },
]

// Bot performance stats (would come from analytics service)
export const MOCK_BOT_STATS = {
  tradesToday: 347,
  tradesThisMonth: 4_820,
  pnlToday: 284.50,
  pnlThisMonth: 3_847.20,
  winRate: 0.78,
  avgTradeSize: 85.40,
  feesGeneratedToday: 34.70,   // Dustify revenue
  pointsGeneratedToday: 5_205,
}
